"""locations_and_zones

Revision ID: 9a814be5f407
Revises: a045570a6634
Create Date: 2026-09-28 08:01:14.508086
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a814be5f407'
down_revision: Union[str, Sequence[str], None] = 'a045570a6634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###