"""device_family

Revision ID: f153c113052f
Revises: c707d933085a
Create Date: 2026-09-23 10:11:58.797699
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f153c113052f'
down_revision: Union[str, Sequence[str], None] = 'c707d933085a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default='simulation', nullable=False))
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###